### ISSUE TITLE
新版报错

### ISSUE THREAD

**Issue by lsw1990** [mushan0x0/wxapp-api-interceptors#11]
const wxApiInterceptors = require('./utils/wxApiInterceptors');
wxApiInterceptors();

App({
  onLaunch: function () {
    wx.showLoading({ title: '登录中...' })
      .then(wx.login)
  },
  globalData: {
  }
})

Cannot read property 'then' of undefined;at App lifeCycleMethod onLaunch function

**Comment by mushan0x0** [comment]
@lsw1990 showLoading 不支持success回调了，直接login也没问题

**Comment by lsw1990** [comment]
为啥不支持成功回调了？以前的版本可以啊

**Comment by lsw1990** [comment]
@mushan0x0 以前的版本是可以的，新版本为什么不支持success回调了？

**Comment by lsw1990** [comment]
@mushan0x0 showLoading的api没有废除success回调啊

**Comment by mushan0x0** [comment]
@lsw1990 搞错了没有不支持，是另外的问题，我有空修复下

**Comment by mushan0x0** [comment]
ok了
