### ISSUE TITLE
wx.pro.request.post这样子调用报then没有找到

### ISSUE THREAD

**Issue by lsw1990** [mushan0x0/wxapp-api-interceptors#12]
wx.pro.request.post('index/ptData', {data:params})
    .then(({res}) => {
      console.log(res)
    })

**Comment by lsw1990** [comment]
目前有点不敢用了，有点不稳定，这里没问题了，别的地方又出问题，纠结

**Comment by mushan0x0** [comment]
@lsw1990  不好意思...已经修复了
