### ISSUE TITLE
使用wx.createAnimation()，animation.opacity(0)会提示animation.opacity is not a function

### ISSUE THREAD

**Issue by ren2436** [mushan0x0/wxapp-api-interceptors#2]
animation 下的所有的方法都失效，这个是BUG还是写作有误？

**Comment by mushan0x0** [comment]
@renxiaomeng 谢谢你的Issues，目前最新版已经解决这个问题

**Comment by renxiaomeng** [comment]
@mushan0x0 使用了你最新的这一版，animation的问题解决了，但出现了更严重的问题：
Cannot read property 'then' of undefined
Promise的方法then、catch、finally 都不可用了

**Comment by ren2436** [comment]
@mushan0x0  使用了你最新的这一版，animation的问题解决了，但出现了另外一个问题：
使用wx.showLoading().then()
Cannot read property 'then' of undefined
showLoading 下的then方法不存在了，其他的接口会不会出现这个问题，暂时还不晓得

**Comment by mushan0x0** [comment]
@renxiaomeng 我看了下api文档，showLoading应该是有一个title是必填的，你也可以在拦截器里设置一个默认title，比如‘加载中...’，这样调用showLoading就可以不必传任何值也可以用了。

**Comment by ren2436** [comment]
@mushan0x0 我在showLoading中加了参数title还是不行，提示 Uncaught TypeError: Cannot read property 'then' of undefined
代码： wx.showLoading({title: '测试'}).then(() => { console.log('success') });

**Comment by mushan0x0** [comment]
@renxiaomeng 感觉是微信的bug，你就直接同步调用showLoading吧。

**Comment by ren2436** [comment]
@mushan0x0 应该不是微信的bug吧，你上一版的这个插件，使用showLoading的then就没问题的
这一版修复animation之后，showLoading的then就出问题了

**Comment by mushan0x0** [comment]
@renxiaomeng 因为我是用的微信提供的接口查询是否是异步api，showLoading返回的是false，所以这是微信的bug

**Comment by mushan0x0** [comment]
@renxiaomeng 我更新了，把showLoading单独排除了

**Comment by ren2436** [comment]
@mushan0x0 发现一个挺有趣的事，用你刚刚更新的代码，把showloading在wxApiInterceptors中注册下，showLoading：{} 即使里边什么都不写，使用then就不会报错，不注册，就会报错，当然解决了animation的bug，是最核心的，感谢了，这个插件真的好用，是我最想要的效果

**Comment by ren2436** [comment]
@mushan0x0  新版的插件，  wx.openLocation、wx.chooseLocation 这两个调不起来微信自带的地图，能否查看下是什么原因，直接就中断了

**Comment by mushan0x0** [comment]
@renxiaomeng 我完善了部分逻辑，你更新看看

**Comment by ren2436** [comment]
@mushan0x0 完美，攒
