### ISSUE TITLE
原生不支持finally,那我应该怎么写hideLoading呢

### ISSUE THREAD

**Issue by lvdong** [mushan0x0/wxapp-api-interceptors#4]
wx.showLoading({title: '登录中...'})
    .then(() => wx.request.post('http://localhost/login', {a:"a"}))
    .then(() => wx.showToast({title: '登录成功'}))
    .catch((err) => {console.log(err)})
像这样用的话。最后应该怎么写。看示例里没有

**Comment by mushan0x0** [comment]
@lvdong 对不起现在才回复，我对finally做了支持，在原生小程序上也可以运行了
