### ISSUE TITLE
wx.requestPayment异常

### ISSUE THREAD

**Issue by SoyMeng** [mushan0x0/wxapp-api-interceptors#8]
使用原生的方式，支付成功后才会进入success
使用插件方式，弹出支付框时就进入then
最开始使用的时候好像是没问题，最近测试就变成上面的情况了，不知道是不是微信改了什么机制

**Comment by mushan0x0** [comment]
@SoyMeng 暂时先wx.old这样访问requestPayment吧，我现在没法测试这个

**Comment by SoyMeng** [comment]
@mushan0x0 模拟器中可以测试，模拟器中弹出一个二维码窗口后就进入then()

**Comment by mushan0x0** [comment]
@SoyMeng 现在我没有项目用到wx.requestPayment。。然后我看文档好像也没有什么改动的地方，要不试试最新的插件看看

**Comment by SoyMeng** [comment]
是的，目前这个方法我暂时使用old。

**Comment by mushan0x0** [comment]
@SoyMeng 最新版已经修复了
